# Generated by Django 5.1.7 on 2025-03-11 14:41

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAutorisations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('acronyme', models.CharField(blank=True, null=True)),
                ('nom', models.CharField(blank=True, null=True)),
                ('prenom', models.CharField(blank=True, null=True)),
                ('mail_1', models.CharField(blank=True, null=True)),
                ('mail_2', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': '"utilisateurs"."agent_autorisations"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgentAutorisationsUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(blank=True, default=django.db.models.functions.datetime.Now, null=True)),
            ],
            options={
                'db_table': '"utilisateurs"."agent_autorisations_update_log"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_demande_avis', models.CharField(blank=True, null=True)),
                ('id_expert_ds', models.CharField(blank=True, null=True, unique=True)),
                ('note', models.CharField(blank=True, null=True)),
                ('favorable', models.BooleanField(blank=True, null=True)),
                ('date_limite', models.DateField()),
                ('date_presentation', models.DateField(blank=True, null=True)),
                ('date_demande_avis', models.DateField()),
                ('date_reponse_avis', models.DateField(blank=True, null=True)),
                ('mode_contact', models.CharField()),
            ],
            options={
                'db_table': '"avis"."avis"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AvisDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"avis"."avis_document"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AvisNature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nature', models.CharField()),
            ],
            options={
                'db_table': '"avis"."avis_nature"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AvisThematique',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('thematique', models.CharField(unique=True)),
            ],
            options={
                'db_table': '"avis"."avis_thematique"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Champ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_ds', models.CharField(blank=True, null=True, unique=True)),
                ('nom', models.CharField()),
                ('description', models.CharField()),
            ],
            options={
                'db_table': '"instruction"."champ"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChampType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(unique=True)),
            ],
            options={
                'db_table': '"instruction"."champ_type"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContactExterne',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(unique=True)),
                ('nom', models.CharField()),
                ('prenom', models.CharField()),
                ('adresse', models.CharField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, null=True)),
                ('siret', models.CharField(blank=True, null=True)),
                ('organisation', models.CharField(blank=True, null=True)),
                ('raison_sociale', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': '"utilisateurs"."contact_externe"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_depot', models.DateField()),
                ('date_fin_instruction', models.DateField(blank=True, null=True)),
                ('soumis_controle', models.BooleanField()),
                ('en_attente_avis', models.BooleanField()),
                ('avis_a_faire', models.BooleanField()),
                ('en_attente_demandeur', models.BooleanField()),
                ('en_attente_validation', models.BooleanField()),
                ('pre_instruction_faite', models.BooleanField()),
                ('id_interlocuteur_ds', models.CharField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': '"instruction"."demande"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DemandeAvis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"avis"."demande_avis"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DemandeBeneficiare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"utilisateurs"."demande_beneficiare"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DemandeChamp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valeur', models.CharField()),
                ('date_saisie', models.DateField()),
                ('geometrie', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': '"instruction"."demande_champ"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DemandeInterlocuteur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_interlocuteur_ds', models.CharField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': '"utilisateurs"."demande_interlocuteur"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DemandeType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(unique=True)),
            ],
            options={
                'db_table': '"instruction"."demande_type"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Demarche',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_ds', models.CharField(blank=True, null=True)),
                ('numero', models.IntegerField(unique=True)),
                ('titre', models.CharField()),
                ('date_creation', models.DateField()),
                ('date_derniere_modif', models.DateField()),
                ('description', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': '"instruction"."demarche"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url_ds', models.CharField(blank=True, null=True)),
                ('emplacement', models.CharField(unique=True)),
                ('description', models.CharField(blank=True, null=True)),
                ('numero', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': '"documents"."document"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentFormat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('format', models.CharField(unique=True)),
            ],
            options={
                'db_table': '"documents"."document_format"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentNature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nature', models.CharField(unique=True)),
            ],
            options={
                'db_table': '"documents"."document_nature"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_ds', models.CharField(blank=True, null=True, unique=True)),
                ('numero', models.IntegerField(unique=True)),
                ('date_depot', models.DateField()),
                ('date_debut_instruction', models.DateField(blank=True, null=True)),
                ('date_fin_instruction', models.DateField(blank=True, null=True)),
                ('id_ds_dossier_parent', models.CharField(blank=True, null=True)),
                ('note', models.CharField(blank=True, null=True)),
                ('nom_dossier', models.CharField()),
                ('emplacement', models.CharField(unique=True)),
                ('date_limite_traitement', models.DateField()),
            ],
            options={
                'db_table': '"instruction"."dossier"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DossierDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"documents"."dossier_document"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DossierGroupe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"instruction"."dossier_groupe"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DossierInstructeur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"utilisateurs"."dossier_instructeur"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DossierType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(unique=True)),
            ],
            options={
                'db_table': '"instruction"."dossier_type"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EtatDemande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(unique=True)),
            ],
            options={
                'db_table': '"instruction"."etat_demande"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EtatDemarche',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(unique=True)),
            ],
            options={
                'db_table': '"instruction"."etat_demarche"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EtatDossier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(unique=True)),
            ],
            options={
                'db_table': '"instruction"."etat_dossier"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_expert_ds', models.CharField(blank=True, null=True, unique=True)),
                ('email', models.CharField(unique=True)),
                ('est_interne', models.BooleanField()),
            ],
            options={
                'db_table': '"avis"."expert"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField()),
            ],
            options={
                'db_table': '"instruction"."groupe"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groupeinstructeur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(unique=True)),
            ],
            options={
                'db_table': '"utilisateurs"."groupeinstructeur"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupeinstructeurDemarche',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_groupeinstructeur_ds', models.CharField(unique=True)),
            ],
            options={
                'db_table': '"utilisateurs"."groupeinstructeur_demarche"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupeinstructeurInstructeur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"utilisateurs"."groupeinstructeur_instructeur"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instructeur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_ds', models.CharField(blank=True, null=True, unique=True)),
                ('email', models.CharField(unique=True)),
            ],
            options={
                'db_table': '"utilisateurs"."instructeur"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_ds', models.CharField()),
                ('body', models.CharField()),
                ('date_envoi', models.DateField()),
                ('piece_jointe', models.BooleanField()),
                ('email_emetteur', models.CharField()),
            ],
            options={
                'db_table': '"instruction"."message"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MessageDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': '"documents"."message_document"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Priorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('niveau', models.CharField(unique=True)),
            ],
            options={
                'db_table': '"instruction"."priorite"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeContactExterne',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(unique=True)),
            ],
            options={
                'db_table': '"utilisateurs"."type_contact_externe"',
                'managed': False,
            },
        ),
    ]
