# Generated by Django 5.1.7 on 2025-03-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeBeneficiaire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"utilisateurs"."demande_beneficiare"',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DemandeBeneficiare',
        ),
    ]
