# Generated by Django 5.1.7 on 2025-03-13 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autorisations', '0002_demandebeneficiaire_delete_demandebeneficiare'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentautorisations',
            options={'managed': False, 'verbose_name_plural': 'Agents Autorisations'},
        ),
        migrations.AlterModelOptions(
            name='avis',
            options={'managed': False, 'verbose_name_plural': 'Avis'},
        ),
        migrations.AlterModelOptions(
            name='demandeavis',
            options={'managed': False, 'verbose_name_plural': 'Demandes avis'},
        ),
    ]
