# Generated by Django 5.1.7 on 2025-03-20 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autorisations', '0003_alter_agentautorisations_options_alter_avis_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='demandebeneficiaire',
            table='"utilisateurs"."demande_beneficiaire"',
        ),
    ]
