# Generated by Django 5.1.7 on 2025-03-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorisations', '0004_alter_demandebeneficiaire_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierBeneficiaire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"utilisateurs"."demande_beneficiaire"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DossierChamp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valeur', models.CharField()),
                ('date_saisie', models.DateField()),
                ('geometrie', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': '"instruction"."dossier_champ"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DossierInterlocuteur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_interlocuteur_ds', models.CharField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': '"utilisateurs"."dossier_interlocuteur"',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DemandeBeneficiaire',
        ),
        migrations.DeleteModel(
            name='DemandeInterlocuteur',
        ),
    ]
