# Generated by Django 5.1.7 on 2025-04-01 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autorisations', '0005_dossierbeneficiaire_dossierchamp_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dossierbeneficiaire',
            table='"utilisateurs"."dossier_beneficiaire"',
        ),
    ]
