# Generated by Django 5.1.7 on 2025-05-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorisations', '0006_alter_dossierbeneficiaire_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierAction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"instruction"."dossier_actions"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EtapeDossier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('etape', models.CharField(unique=True)),
            ],
            options={
                'db_table': '"instruction"."etape_dossier"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModificationType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modification', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"instruction"."modification_type"',
                'managed': False,
            },
        ),
    ]
