# Generated by Django 5.1.7 on 2025-06-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorisations', '0007_dossieraction_etapedossier_modificationtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"instruction"."action"',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ModificationType',
        ),
    ]
