# Generated by Django 5.1.7 on 2025-07-03 05:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorisations', '0008_action_delete_modificationtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': '"instruction"."dossier_notes"',
                'managed': False,
            },
        ),
    ]
