# Generated by Django 5.1.7 on 2025-07-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorisations', '0009_dossiernote'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierNoteDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"instruction"."dossier_note_documents"',
                'managed': False,
            },
        ),
    ]
