# Generated by Django 5.1.7 on 2025-07-04 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autorisations', '0010_dossiernotedocument'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dossiernotedocument',
            table='"documents"."dossier_note_documents"',
        ),
    ]
