# Generated by Django 5.1.7 on 2025-08-07 05:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorisations', '0011_alter_dossiernotedocument_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentStatut',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('statut', models.CharField(unique=True)),
            ],
            options={
                'db_table': '"documents"."document_statut"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DossierManifestationLiaison',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"instruction"."dossier_manifestation_liaison"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DossierManifSportive',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('geometrie', models.JSONField(blank=True, null=True)),
                ('emplacement', models.TextField()),
                ('archive', models.BooleanField(default=False)),
                ('nom_organisateur', models.TextField()),
                ('prenom_organisateur', models.TextField()),
                ('qualite_declarant', models.TextField()),
                ('structure', models.TextField()),
                ('adresse', models.TextField()),
                ('numero_telephone', models.TextField()),
                ('email_structure', models.TextField()),
                ('nom_dossier', models.TextField()),
                ('numero_dossier_declaration_manifestations', models.IntegerField(unique=True)),
                ('etat_dossier', models.TextField()),
                ('date_depot', models.DateTimeField()),
                ('date_debut_evenement', models.DateTimeField()),
                ('date_fin_evenement', models.DateTimeField()),
                ('emprise_voie_publique', models.TextField()),
                ('evenement_competition', models.BooleanField()),
                ('description', models.TextField()),
                ('observation', models.TextField()),
                ('activite', models.TextField()),
                ('affilie_federation_delegataire', models.BooleanField()),
                ('nombre_participants', models.IntegerField()),
                ('nombre_max_spectateurs', models.IntegerField()),
                ('nombre_organisateurs', models.IntegerField()),
                ('nombre_vehicules_accompagnement', models.IntegerField()),
                ('depart_groupe_participants', models.BooleanField()),
                ('circulation_groupee_participants', models.BooleanField()),
                ('respect_code_route', models.BooleanField()),
                ('priorite_passage', models.BooleanField()),
                ('usage_exclusif_temporaire_chaussee', models.BooleanField()),
                ('usage_privatif_chaussee', models.BooleanField()),
                ('precisions_voies_et_horaires', models.TextField()),
                ('vehicule_ouverture', models.BooleanField()),
                ('vehicule_tete_course', models.BooleanField()),
                ('vehicule_fin_course', models.BooleanField()),
                ('autres_vehicules_organisation', models.BooleanField()),
                ('nombre_signaleurs', models.IntegerField()),
                ('signaleurs_postes_fixes', models.IntegerField()),
                ('signaleurs_mobiles_voitures', models.IntegerField()),
                ('signaleurs_mobiles_motos', models.IntegerField()),
                ('encadrement_police_municipale', models.BooleanField()),
                ('details_encadrement_police_municipale', models.TextField()),
                ('convention_police_nationale', models.BooleanField()),
                ('details_convention_police_nationale', models.TextField()),
                ('nom_coordinateur_securite', models.TextField()),
                ('prenom_coordinateur_securite', models.TextField()),
                ('telephone_coordinateur_securite', models.TextField()),
                ('email_coordinateur_securite', models.TextField()),
                ('nom_contact', models.TextField()),
                ('prenom_contact', models.TextField()),
                ('telephone_contact', models.TextField()),
                ('autres_contacts_utiles', models.TextField()),
                ('budget_depasse_100k', models.BooleanField()),
                ('manifestation_lucrative_plus_1500', models.BooleanField()),
                ('manifestation_titre_national_international', models.BooleanField()),
                ('manifestation_vehicules_hors_voies_ouvertes', models.BooleanField()),
                ('charte_dispense_natura_2000', models.BooleanField()),
                ('lieux_pdesi', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('signataire_charte_balisage', models.BooleanField()),
                ('description_balisage', models.TextField()),
            ],
            options={
                'db_table': '"instruction"."dossier_manif_sportive"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DossierRelecteurJuridique',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"utilisateurs"."dossier_relecteur_juridique"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DossierRelecteurQualite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"utilisateurs"."dossier_relecteur_qualite"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DossierSignataire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"utilisateurs"."dossier_signataire"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DossierValideur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"utilisateurs"."dossier_valideur"',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DossierNoteDocument',
        ),
    ]
