# Generated by Django 5.1.7 on 2025-08-14 07:00

import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorisations', '0012_documentstatut_dossiermanifestationliaison_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('email_from', models.EmailField(max_length=254)),
                ('sujet', models.CharField(max_length=255)),
                ('template', models.CharField(max_length=100)),
                ('context', models.JSONField(default=dict)),
                ('statut', models.CharField(choices=[('À envoyer', 'À envoyer'), ('Envoyé', 'Envoyé'), ('Échec', 'Échec')], default='À envoyer', max_length=20)),
                ('try_count', models.IntegerField(default=0)),
                ('derniere_tentative_envoi', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('derniere_erreur', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"utilisateurs"."email_outbox"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SynchronisationEtat',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('en_cours', models.BooleanField(default=False)),
                ('date_maj', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': '"instruction"."synchronisation_etat"',
                'managed': False,
            },
        ),
    ]
