# Generated by Django 5.1.7 on 2025-08-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autorisations', '0013_emailoutbox_synchronisationetat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dossieravis',
            options={'managed': False, 'verbose_name_plural': 'Dossiers avis'},
        ),
        migrations.AlterModelTable(
            name='dossieravis',
            table='"avis"."dossier_avis"',
        ),
    ]
