# Generated by Django 5.1.7 on 2025-09-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorisations', '0014_alter_dossieravis_options_alter_dossieravis_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierRelecteur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('demande_relecture', models.TextField()),
                ('reponse_relecture', models.TextField()),
                ('relu', models.BooleanField(default=False)),
            ],
            options={
                'db_table': '"utilisateurs"."dossier_relecteur_juridique"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DossierRelecteurDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"documents"."dossier_relecteur_document"',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DossierRelecteurJuridique',
        ),
    ]
