# Generated by Django 5.1.7 on 2025-09-04 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autorisations', '0015_dossierrelecteur_dossierrelecteurdocument_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dossierrelecteur',
            table='"utilisateurs"."dossier_relecteur"',
        ),
    ]
