# Generated by Django 5.1.7 on 2025-10-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorisations', '0016_alter_dossierrelecteur_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisManifSportive',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_avis_manif_sportive', models.IntegerField()),
                ('etat', models.TextField(blank=True, null=True)),
                ('service', models.TextField(blank=True, null=True)),
                ('date_demande', models.DateTimeField(blank=True, null=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('reponse_avis', models.TextField(blank=True, null=True)),
                ('prescriptions', models.TextField(blank=True, null=True)),
                ('objet_demande', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'instruction"."avis_manif_sportive',
                'managed': False,
            },
        ),
    ]
