# Generated by Django 5.1.7 on 2026-03-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorisations', '0017_avismanifsportive'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierEnvoiActe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"utilisateurs"."dossier_envoi_acte"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DossierIntermediaireSignature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"utilisateurs"."dossier_intermediaire_signature"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DossierPublicationRAA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"utilisateurs"."dossier_publication_raa"',
                'managed': False,
            },
        ),
    ]
