# Generated by Django 5.1.7 on 2026-04-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorisations', '0018_dossierenvoiacte_dossierintermediairesignature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierManifSportiveDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"documents"."dossier_manif_sportive_document"',
                'managed': False,
            },
        ),
    ]
