# Generated by Django 5.1.7 on 2026-04-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorisations', '0019_dossiermanifsportivedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionsPossibles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('present_sur_dn', models.BooleanField()),
                ('coeur_de_parc', models.BooleanField(blank=True, null=True)),
                ('type_manif_sportive', models.CharField(blank=True, choices=[('Dossier DN', 'Dossier DN'), ('Dossier DM', 'Dossier DM'), ('Dossier complet', 'Dossier complet')], max_length=20, null=True)),
            ],
            options={
                'db_table': '"instruction"."actions_possibles"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChangementEtape',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.TextField(unique=True)),
                ('code', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': '"instruction"."changement_etape"',
                'managed': False,
            },
        ),
    ]
