# Generated by Django 5.1.7 on 2026-04-21 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autorisations', '0020_actionspossibles_changementetape'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionspossibles',
            options={'managed': False, 'verbose_name': 'Action possible', 'verbose_name_plural': 'Actions possibles'},
        ),
    ]
