# Generated by Django 5.1.7 on 2026-09-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorisations', '0023_avismanifsportive_relation_multiple'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierManifSportiveInstructeur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"utilisateurs"."dossier_manif_sportive_instructeur"',
                'managed': False,
            },
        ),
    ]
