from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autorisations", "0024_dossiermanifsportiveinstructeur"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS utilisateurs.destinataire_notification (
                            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            libelle varchar(150) NOT NULL,
                            email varchar(254) NOT NULL UNIQUE,
                            actif boolean NOT NULL DEFAULT true
                        );
                        COMMENT ON TABLE utilisateurs.destinataire_notification IS
                            'Adresses génériques proposées uniquement pour les notifications manuelles AGIDA.';
                    """,
                    reverse_sql="DROP TABLE IF EXISTS utilisateurs.destinataire_notification;",
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="instructeur",
                    name="id_agent_autorisations",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        db_column="id_agent_autorisations",
                        on_delete=models.RESTRICT,
                        to="autorisations.agentautorisations",
                    ),
                ),
                migrations.CreateModel(
                    name="DestinataireNotification",
                    fields=[
                        ("id", models.AutoField(primary_key=True, serialize=False)),
                        ("libelle", models.CharField(max_length=150)),
                        ("email", models.EmailField(max_length=254, unique=True)),
                        ("actif", models.BooleanField(default=True)),
                    ],
                    options={
                        "verbose_name": "Destinataire de notification",
                        "verbose_name_plural": "Destinataires de notification",
                        "db_table": '"utilisateurs"."destinataire_notification"',
                        "ordering": ("libelle", "email"),
                        "managed": False,
                    },
                ),
            ],
        ),
    ]
