from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [("autorisations", "0025_destinatairenotification")]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $migration$
                        BEGIN
                        -- Certaines bases sont préparées par un administrateur SQL.
                        -- Ne pas lancer de DDL sur les objets déjà présents : le compte
                        -- applicatif peut les utiliser sans en être propriétaire.
                        IF to_regclass('instruction.ensemble_dossiers') IS NULL THEN
                        CREATE TABLE instruction.ensemble_dossiers (
                            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            date_creation timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            cree_par integer NULL REFERENCES utilisateurs.instructeur(id)
                                ON DELETE SET NULL
                        );
                        END IF;
                        IF to_regclass('instruction.ensemble_dossiers_createur_idx') IS NULL THEN
                        CREATE INDEX ensemble_dossiers_createur_idx
                            ON instruction.ensemble_dossiers(cree_par);
                        END IF;
                        IF NOT EXISTS (
                            SELECT 1 FROM information_schema.columns
                            WHERE table_schema = 'instruction' AND table_name = 'dossier'
                              AND column_name = 'id_ensemble_dossiers'
                        ) THEN
                        ALTER TABLE instruction.dossier
                            ADD COLUMN id_ensemble_dossiers integer NULL
                            REFERENCES instruction.ensemble_dossiers(id) ON DELETE SET NULL;
                        END IF;
                        IF to_regclass('instruction.dossier_ensemble_dossiers_idx') IS NULL THEN
                        CREATE INDEX dossier_ensemble_dossiers_idx
                            ON instruction.dossier(id_ensemble_dossiers);
                        END IF;
                        END $migration$;
                    """,
                    reverse_sql="""
                        ALTER TABLE instruction.dossier DROP COLUMN id_ensemble_dossiers;
                        DROP TABLE instruction.ensemble_dossiers;
                    """,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="EnsembleDossiers",
                    fields=[
                        ("id", models.AutoField(primary_key=True, serialize=False)),
                        ("date_creation", models.DateTimeField(default=django.utils.timezone.now)),
                        ("cree_par", models.ForeignKey(
                            to="autorisations.instructeur", on_delete=models.SET_NULL,
                            db_column="cree_par", null=True, blank=True,
                            related_name="ensembles_dossiers_crees",
                        )),
                    ],
                    options={
                        "managed": False,
                        "db_table": '"instruction"."ensemble_dossiers"',
                        "verbose_name": "Ensemble de dossiers",
                        "verbose_name_plural": "Ensembles de dossiers",
                    },
                ),
                migrations.AddField(
                    model_name="dossier", name="id_ensemble_dossiers",
                    field=models.ForeignKey(
                        to="autorisations.ensembledossiers", on_delete=models.SET_NULL,
                        db_column="id_ensemble_dossiers", null=True, blank=True,
                        related_name="dossiers",
                    ),
                ),
            ],
        ),
    ]
