from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("autorisations", "0026_ensemble_dossiers")]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $migration$
                        BEGIN
                            IF NOT EXISTS (
                                SELECT 1 FROM information_schema.columns
                                WHERE table_schema = 'instruction' AND table_name = 'dossier'
                                  AND column_name = 'date_debut_activite'
                            ) THEN
                                ALTER TABLE instruction.dossier
                                    ADD COLUMN date_debut_activite TIMESTAMP WITH TIME ZONE NULL;
                            END IF;

                            IF to_regclass('instruction.demarche_date_activite_champ') IS NULL THEN
                                CREATE TABLE instruction.demarche_date_activite_champ (
                                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    id_demarche integer NOT NULL REFERENCES instruction.demarche(id) ON DELETE CASCADE,
                                    id_champ integer NOT NULL REFERENCES instruction.champ(id) ON DELETE RESTRICT,
                                    ordre smallint NOT NULL
                                );
                            END IF;

                            IF to_regclass('instruction.demarche_date_activite_champ_unique') IS NULL THEN
                                CREATE UNIQUE INDEX demarche_date_activite_champ_unique
                                    ON instruction.demarche_date_activite_champ(id_demarche, id_champ);
                            END IF;

                            IF to_regclass('instruction.demarche_date_activite_ordre_unique') IS NULL THEN
                                CREATE UNIQUE INDEX demarche_date_activite_ordre_unique
                                    ON instruction.demarche_date_activite_champ(id_demarche, ordre);
                            END IF;
                        END $migration$;
                    """,
                    reverse_sql="""
                        ALTER TABLE instruction.dossier DROP COLUMN IF EXISTS date_debut_activite;
                        DROP TABLE IF EXISTS instruction.demarche_date_activite_champ;
                    """,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="dossier",
                    name="date_debut_activite",
                    field=models.DateTimeField(blank=True, null=True),
                ),
                migrations.CreateModel(
                    name="DemarcheDateActiviteChamp",
                    fields=[
                        ("id", models.AutoField(primary_key=True, serialize=False)),
                        ("ordre", models.PositiveSmallIntegerField(default=1)),
                        ("id_demarche", models.ForeignKey(
                            to="autorisations.demarche", on_delete=models.CASCADE,
                            db_column="id_demarche", related_name="date_activite_champs",
                        )),
                        ("id_champ", models.ForeignKey(
                            to="autorisations.champ", on_delete=models.RESTRICT,
                            db_column="id_champ", related_name="configurations_date_activite",
                        )),
                    ],
                    options={
                        "managed": False,
                        "db_table": '"instruction"."demarche_date_activite_champ"',
                        "ordering": ("ordre", "id"),
                    },
                ),
            ],
        ),
    ]
