from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("autorisations", "0027_demarche_date_activite")]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $migration$
                        BEGIN
                            IF to_regclass('instruction.demarche_configuration_tableau') IS NULL THEN
                                CREATE TABLE instruction.demarche_configuration_tableau (
                                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    id_demarche integer NOT NULL UNIQUE
                                        REFERENCES instruction.demarche(id) ON DELETE CASCADE,
                                    afficher_date_activite_dans_vue_ensemble boolean NOT NULL DEFAULT TRUE
                                );
                            END IF;
                        END $migration$;
                    """,
                    reverse_sql="""
                        DROP TABLE IF EXISTS instruction.demarche_configuration_tableau;
                    """,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="DemarcheConfigurationTableau",
                    fields=[
                        ("id", models.AutoField(primary_key=True, serialize=False)),
                        ("afficher_date_activite_dans_vue_ensemble", models.BooleanField(default=True)),
                        ("id_demarche", models.OneToOneField(
                            to="autorisations.demarche", on_delete=models.CASCADE,
                            db_column="id_demarche", related_name="configuration_tableau",
                        )),
                    ],
                    options={
                        "managed": False,
                        "db_table": '"instruction"."demarche_configuration_tableau"',
                    },
                ),
            ],
        ),
    ]
