from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("autorisations", "0028_demarche_configuration_tableau")]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $migration$
                        BEGIN
                            IF to_regclass('instruction.demarche_colonne_vue_ensemble') IS NULL THEN
                                CREATE TABLE instruction.demarche_colonne_vue_ensemble (
                                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    id_demarche integer NOT NULL
                                        REFERENCES instruction.demarche(id) ON DELETE CASCADE,
                                    tableau varchar(30) NOT NULL,
                                    colonne varchar(50) NOT NULL,
                                    affiche boolean NOT NULL DEFAULT TRUE,
                                    CONSTRAINT demarche_colonne_vue_ensemble_unique
                                        UNIQUE (id_demarche, tableau, colonne)
                                );
                            END IF;
                        END $migration$;
                    """,
                    reverse_sql="""
                        DROP TABLE IF EXISTS instruction.demarche_colonne_vue_ensemble;
                    """,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="DemarcheColonneVueEnsemble",
                    fields=[
                        ("id", models.AutoField(primary_key=True, serialize=False)),
                        ("tableau", models.CharField(max_length=30)),
                        ("colonne", models.CharField(max_length=50)),
                        ("affiche", models.BooleanField(default=True)),
                        ("id_demarche", models.ForeignKey(
                            to="autorisations.demarche", on_delete=models.CASCADE,
                            db_column="id_demarche", related_name="configurations_colonnes_vue_ensemble",
                        )),
                    ],
                    options={
                        "managed": False,
                        "db_table": '"instruction"."demarche_colonne_vue_ensemble"',
                    },
                ),
            ],
        ),
    ]
