from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("autorisations", "0029_demarche_colonne_vue_ensemble")]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS instruction.demarche_date_activite_configuration (
                            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            id_demarche integer NOT NULL UNIQUE
                                REFERENCES instruction.demarche(id) ON DELETE CASCADE,
                            delai_alerte_jours smallint NOT NULL DEFAULT 30
                                CHECK (delai_alerte_jours >= 0),
                            couleur_alerte varchar(7) NOT NULL DEFAULT '#d97706',
                            couleur_passee varchar(7) NOT NULL DEFAULT '#b91c1c'
                        );
                    """,
                    reverse_sql="""
                        DROP TABLE IF EXISTS instruction.demarche_date_activite_configuration;
                    """,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="DemarcheDateActiviteConfiguration",
                    fields=[
                        ("id", models.AutoField(primary_key=True, serialize=False)),
                        ("delai_alerte_jours", models.PositiveSmallIntegerField(default=30)),
                        ("couleur_alerte", models.CharField(default="#d97706", max_length=7)),
                        ("couleur_passee", models.CharField(default="#b91c1c", max_length=7)),
                        ("id_demarche", models.OneToOneField(
                            to="autorisations.demarche", on_delete=models.CASCADE,
                            db_column="id_demarche", related_name="configuration_date_activite",
                        )),
                    ],
                    options={
                        "managed": False,
                        "db_table": '"instruction"."demarche_date_activite_configuration"',
                    },
                ),
            ],
        ),
    ]
