from django.db import migrations, models
import django.db.models.deletion


SQL = """
DO $migration$
BEGIN
IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'instruction' AND table_name = 'dossier'
      AND column_name = 'nom_dossier_genere'
) THEN
    ALTER TABLE instruction.dossier ADD COLUMN nom_dossier_genere text NULL;
END IF;

IF to_regclass('instruction.demarche_nom_dossier_regle') IS NULL THEN
CREATE TABLE instruction.demarche_nom_dossier_regle (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_demarche integer NOT NULL REFERENCES instruction.demarche(id) ON DELETE CASCADE,
    libelle varchar(150) NOT NULL DEFAULT '',
    ordre smallint NOT NULL CHECK (ordre > 0),
    actif boolean NOT NULL DEFAULT true,
    CONSTRAINT demarche_nom_dossier_regle_ordre_unique UNIQUE (id_demarche, ordre)
);
END IF;

IF to_regclass('instruction.demarche_nom_dossier_element') IS NULL THEN
CREATE TABLE instruction.demarche_nom_dossier_element (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_regle integer NOT NULL REFERENCES instruction.demarche_nom_dossier_regle(id) ON DELETE CASCADE,
    ordre smallint NOT NULL CHECK (ordre > 0),
    type_element varchar(20) NOT NULL CHECK (type_element IN ('texte', 'champ_dn', 'attribut')),
    texte text NULL,
    id_champ integer NULL REFERENCES instruction.champ(id) ON DELETE RESTRICT,
    attribut varchar(80) NULL,
    transformation varchar(30) NOT NULL DEFAULT 'aucune'
        CHECK (transformation IN ('aucune', 'majuscules', 'minuscules', 'date', 'date_heure')),
    CONSTRAINT demarche_nom_dossier_element_ordre_unique UNIQUE (id_regle, ordre),
    CONSTRAINT demarche_nom_dossier_element_source_check CHECK (
        (type_element = 'texte' AND texte IS NOT NULL AND id_champ IS NULL AND attribut IS NULL AND transformation = 'aucune') OR
        (type_element = 'champ_dn' AND texte IS NULL AND id_champ IS NOT NULL AND attribut IS NULL) OR
        (type_element = 'attribut' AND texte IS NULL AND id_champ IS NULL AND attribut IS NOT NULL)
    )
);
END IF;
END;
$migration$;
"""


class Migration(migrations.Migration):
    dependencies = [("autorisations", "0033_demarche_colonne_vue_ensemble_ordre")]
    operations = [migrations.SeparateDatabaseAndState(
        database_operations=[migrations.RunSQL(SQL, reverse_sql=migrations.RunSQL.noop)],
        state_operations=[
            migrations.AddField(
                model_name="dossier", name="nom_dossier_genere",
                field=models.CharField(blank=True, null=True),
            ),
            migrations.CreateModel(
                name="DemarcheNomDossierRegle",
                fields=[
                    ("id", models.AutoField(primary_key=True, serialize=False)),
                    ("libelle", models.CharField(max_length=150, blank=True)),
                    ("ordre", models.PositiveSmallIntegerField()),
                    ("actif", models.BooleanField(default=True)),
                    ("id_demarche", models.ForeignKey(to="autorisations.demarche", on_delete=django.db.models.deletion.CASCADE, db_column="id_demarche", related_name="regles_nom_dossier")),
                ],
                options={"managed": False, "db_table": '"instruction"."demarche_nom_dossier_regle"', "ordering": ("ordre", "id"), "constraints": [models.UniqueConstraint(fields=["id_demarche", "ordre"], name="demarche_nom_dossier_regle_ordre_unique")]},
            ),
            migrations.CreateModel(
                name="DemarcheNomDossierElement",
                fields=[
                    ("id", models.AutoField(primary_key=True, serialize=False)),
                    ("ordre", models.PositiveSmallIntegerField()),
                    ("type_element", models.CharField(max_length=20, choices=[("texte", "Texte fixe"), ("champ_dn", "Champ DN"), ("attribut", "Donnée AGIDA")])),
                    ("texte", models.TextField(blank=True, null=True)),
                    ("attribut", models.CharField(max_length=80, blank=True, null=True)),
                    ("transformation", models.CharField(max_length=30, default="aucune", choices=[("aucune", "Aucune"), ("majuscules", "MAJUSCULES"), ("minuscules", "minuscules"), ("date", "Date · JJ/MM/AAAA"), ("date_heure", "Date et heure · JJ/MM/AAAA HHhMM")])),
                    ("id_regle", models.ForeignKey(to="autorisations.demarchenomdossierregle", on_delete=django.db.models.deletion.CASCADE, db_column="id_regle", related_name="elements")),
                    ("id_champ", models.ForeignKey(to="autorisations.champ", on_delete=django.db.models.deletion.RESTRICT, db_column="id_champ", blank=True, null=True)),
                ],
                options={"managed": False, "db_table": '"instruction"."demarche_nom_dossier_element"', "ordering": ("ordre", "id"), "constraints": [models.UniqueConstraint(fields=["id_regle", "ordre"], name="demarche_nom_dossier_element_ordre_unique")]},
            ),
        ],
    )]
