site_name: Autorisations – Documentation
site_url: http://autorisations.pnrun.local/

theme:
  name: material
  language: fr
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Basculer en mode sombre
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Basculer en mode clair
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - content.code.copy
    - navigation.indexes

use_directory_urls: false

nav:
  - Accueil: index.md
  - Prérequis:
      - Accès: prerequis/acces.md
      - Authentification: prerequis/authentification.md
      - Espace de stockage: prerequis/espace-stockage.md
      - Habilitations: prerequis/habilitations.md
  - Onglets de navigation:
      - Réception: onglets/reception.md
      - Vue d'ensemble: onglets/vue-ensemble.md
      - Mes dossiers: onglets/mes-dossiers.md
      - Mes Avis:
          - Vision Expert: onglets/vision-expert.md
          - Vision Demandeur: onglets/vision-demandeur.md
      - Requêtes: onglets/requetes.md
  - Les passages d'étape:
      - Le déroulement de l'instruction: etapes/deroulement-instruction.md
      - Passer en pré-instruction: etapes/preinstruction.md
      - Passer en instruction: etapes/instruction.md
      - Demander des compléments: etapes/demander-complements.md
      - Repasser en instruction: etapes/repasser-instruction.md
      - Faire valider une demande d'avis: etapes/faire-valider-avis.md
      - Faire valider le projet d'acte: etapes/faire-valider-acte.md
      - Valider le modèle de demande d'avis et le projet d'acte: etapes/valider-avis-et-acte.md
      - Valider et envoyer pour relecture qualité: etapes/valider-acte.md
      - Prêt à la signature: etapes/pret-a-la-signature.md
      - Classer le dossier comme non soumis à autorisation: etapes/non-soumis-a-autorisation.md
      - Classer le dossier comme refusé: etapes/refuse.md
      - Classer le dossier comme accepté: etapes/accepte.md
      - Avis envoyé: etapes/avis-envoye.md
      - Transmettre l'acte signé: etapes/transmettre-acte-signe.md
      - Envoyer l'acte: etapes/envoyer-acte.md
      - Partager l'acte par mail: etapes/partager_acte_par_mail.md
  - Un dossier:
      - Onglet Formulaire:
        - L'entête : dossier/formulaire/entete.md
        - Timeline: dossier/formulaire/timeline.md
        - Pannel de droite: dossier/formulaire/pannel-droite.md
        - Champs: dossier/formulaire/champs.md
        - Carto: dossier/formulaire/carto.md
      - Onglet Messagerie: dossier/messagerie.md
      - Onglet Consultation:
        - Consultation : dossier/consultation/consultation.md
        - Nouvelle demande d'avis: dossier/consultation/nouvelle-demande-avis.md
        - Ajouter un avis existant: dossier/consultation/ajouter-avis-existant.md
      - Stockage physique: dossier/stockage.md
      - Notifications: dossier/notifications.md
  - Les manifestations sportives:
      - Réception: manif_sportive/reception_manif_sportive.md
      - Dossier Déclaration Manifestations: manif_sportive/dossier_dm.md
  - Developpeur:
      - Structure du projet: developer/structure-projet.md
      - Django: developer/django.md
      - Authentification: developer/authentification.md
      - Stockage: developer/stockage.md
      - Les logs: developer/logs.md
      - La documentation: developer/documentation.md
      - Base de données: developer/bdd.md
      - Déploiement: developer/deploiement.md
      - API Démarche Numérique: developer/api-demarche-numérique.md
      - API Déclaration Manifestations: developer/api-declaration-manifestations.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed

extra_css:
  - styles/tables.css